# NEXT WORD PREDICTION

In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np

In [2]:
df = pd.read_csv("tmdb_5000_movies.csv")
df

budget                                             genres  \
0     237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...         ...                                                ...   
4798     220000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799       9000  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800          0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801          0                                                 []   
4802          0                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
0     [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4     [{"id": 818, "name": "based on novel"}, {"id":...                en   
...                                                 ...               ...   
4798  [{"id": 5616, "name": "united states\u2013mexi...                es   
4799                                                 []                en   
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...                en   
4801                                                 []                en   
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...                en   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                               overview  popularity  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577   
1     Captain Barbossa, long believed to be dead, ha...  139.082615   
2     A cryptic message from Bond’s past sends him o...  107.376788   
3     Following the death of District Attorney Harve...  112.312950   
4     John Carter is a war-weary, former military ca...   43.926995   
...                                                 ...         ...   
4798  El Mariachi just wants to play his guitar and ...   14.269792   
4799  A newlywed couple's honeymoon is upended by th...    0.642552   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476   
4801  When ambitious New York attorney Sam is sent t...    0.857008   
4802  Ever since the second grade when he first saw ... 

In [3]:
# to display the fist 5 value of the data set
df.head(5)

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [4]:
# We need only the original title attribute
df = df["original_title"]

In [5]:
df

0                                         Avatar
1       Pirates of the Caribbean: At World's End
2                                        Spectre
3                          The Dark Knight Rises
4                                    John Carter
                          ...                   
4798                                 El Mariachi
4799                                   Newlyweds
4800                   Signed, Sealed, Delivered
4801                            Shanghai Calling
4802                           My Date with Drew
Name: original_title, Length: 4803, dtype: object

In [6]:
# we need to convert the text data into numbers for testing

# we'll convert the column from  pandas object to list type by using  

movie_name = df.to_list()

In [7]:
movie_name

['Avatar',
 "Pirates of the Caribbean: At World's End",
 'Spectre',
 'The Dark Knight Rises',
 'John Carter',
 'Spider-Man 3',
 'Tangled',
 'Avengers: Age of Ultron',
 'Harry Potter and the Half-Blood Prince',
 'Batman v Superman: Dawn of Justice',
 'Superman Returns',
 'Quantum of Solace',
 "Pirates of the Caribbean: Dead Man's Chest",
 'The Lone Ranger',
 'Man of Steel',
 'The Chronicles of Narnia: Prince Caspian',
 'The Avengers',
 'Pirates of the Caribbean: On Stranger Tides',
 'Men in Black 3',
 'The Hobbit: The Battle of the Five Armies',
 'The Amazing Spider-Man',
 'Robin Hood',
 'The Hobbit: The Desolation of Smaug',
 'The Golden Compass',
 'King Kong',
 'Titanic',
 'Captain America: Civil War',
 'Battleship',
 'Jurassic World',
 'Skyfall',
 'Spider-Man 2',
 'Iron Man 3',
 'Alice in Wonderland',
 'X-Men: The Last Stand',
 'Monsters University',
 'Transformers: Revenge of the Fallen',
 'Transformers: Age of Extinction',
 'Oz: The Great and Powerful',
 'The Amazing Spider-Man 2',

In [8]:
# we'll use tensorflow to map each word with some unique numbers

tokenizer = tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(movie_name)
seq = tokenizer.texts_to_sequences(movie_name)

In [9]:
seq[:10]

[[1564],
 [210, 2, 1, 431, 47, 432, 72],
 [1565],
 [1, 52, 211, 1566],
 [212, 601],
 [213, 8, 21],
 [1567],
 [902, 146, 2, 1568],
 [110, 214, 4, 1, 433, 53, 147],
 [173, 340, 261, 85, 2, 903]]

In [10]:
# to check which number is mapped to which word we can use tokenizer.word_index

tokenizer.word_index

{'the': 1,
 'of': 2,
 'a': 3,
 'and': 4,
 'in': 5,
 '2': 6,
 'to': 7,
 'man': 8,
 'i': 9,
 'love': 10,
 'with': 11,
 'on': 12,
 'me': 13,
 'my': 14,
 'movie': 15,
 'you': 16,
 'dead': 17,
 'last': 18,
 'for': 19,
 'from': 20,
 '3': 21,
 'good': 22,
 'big': 23,
 'day': 24,
 'house': 25,
 'ii': 26,
 'american': 27,
 'men': 28,
 'it': 29,
 'story': 30,
 'life': 31,
 'black': 32,
 'girl': 33,
 'all': 34,
 'out': 35,
 'time': 36,
 'night': 37,
 'is': 38,
 'world': 39,
 'days': 40,
 'star': 41,
 'part': 42,
 'new': 43,
 'de': 44,
 'little': 45,
 'la': 46,
 'at': 47,
 'up': 48,
 'an': 49,
 'die': 50,
 'city': 51,
 'dark': 52,
 'blood': 53,
 'game': 54,
 'one': 55,
 'red': 56,
 'blue': 57,
 'your': 58,
 'iii': 59,
 'kill': 60,
 'war': 61,
 'white': 62,
 'street': 63,
 'lost': 64,
 'christmas': 65,
 'legend': 66,
 'wild': 67,
 'how': 68,
 'road': 69,
 'boys': 70,
 'high': 71,
 'end': 72,
 'down': 73,
 'home': 74,
 'hard': 75,
 'boy': 76,
 'year': 77,
 'like': 78,
 'x': 79,
 'bad': 80,
 'do': 81

In [11]:
# x conatins the input data
X=[]
# Y will contain the output data
Y=[]
total_words_dropped =0

# using for operation to iterate over the each word in seq

for i in seq:
    if len(i) > 1:
        for index in range(1, len(i)):
        	X.append(i[:index])
        	Y.append(i[index])
        else:
        	total_words_dropped += 1
print("The total words Dropped are :", total_words_dropped)

The total words Dropped are : 3800


In [12]:
X[:10]

[[210],
 [210, 2],
 [210, 2, 1],
 [210, 2, 1, 431],
 [210, 2, 1, 431, 47],
 [210, 2, 1, 431, 47, 432],
 [1],
 [1, 52],
 [1, 52, 211],
 [212]]

In [13]:
Y[:10]

[2, 1, 431, 47, 432, 72, 52, 211, 1566, 601]

In [14]:
# the length of list is varying so wee need to make the length equal by using the keras
X = tf.keras.preprocessing.sequence.pad_sequences(X)
X

array([[  0,   0,   0, ...,   0,   0, 210],
       [  0,   0,   0, ...,   0, 210,   2],
       [  0,   0,   0, ..., 210,   2,   1],
       ...,
       [  0,   0,   0, ...,   0,   0,  14],
       [  0,   0,   0, ...,   0,  14, 300],
       [  0,   0,   0, ...,  14, 300,  11]])

In [15]:
# number of rows and column used to make the list equal
X.shape

(8483, 14)

In [16]:
Y = tf.keras.utils.to_categorical(Y)
Y

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [17]:
# number of rows and column used to make the list equal
Y.shape

(8483, 5045)

In [18]:
# vocab_size will used to store th length of the vocabulary
vocab_size = len(tokenizer.word_index) + 1
vocab_size

5045

In [19]:
# now training the model 

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, 14),
    tf.keras.layers.LSTM(100, return_sequences=True),
    tf.keras.layers.LSTM(100),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(vocab_size,activation='softmax')

])

In [20]:
model

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 14)          70630     
                                                                 
 lstm (LSTM)                 (None, None, 100)         46000     
                                                                 
 lstm_1 (LSTM)               (None, 100)               80400     
                                                                 
 dense (Dense)               (None, 100)               10100     
                                                                 
 dense_1 (Dense)             (None, 5045)              509545    
                                                                 
Total params: 716,675
Trainable params: 716,675
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.compile(optimizer ='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [23]:
model.fit(X,Y,epochs=10)

Epoch 1/10
266/266 [==============================] - 11s 31ms/step - loss: 7.7840 - accuracy: 0.0606
Epoch 2/10
266/266 [==============================] - 8s 31ms/step - loss: 7.1372 - accuracy: 0.0613
Epoch 3/10
266/266 [==============================] - 8s 31ms/step - loss: 6.9503 - accuracy: 0.0633
Epoch 4/10
266/266 [==============================] - 8s 31ms/step - loss: 6.7151 - accuracy: 0.0871
Epoch 5/10
266/266 [==============================] - 8s 31ms/step - loss: 6.5368 - accuracy: 0.0909
Epoch 6/10
266/266 [==============================] - 8s 31ms/step - loss: 6.4190 - accuracy: 0.0950
Epoch 7/10
266/266 [==============================] - 8s 31ms/step - loss: 6.3302 - accuracy: 0.0962
Epoch 8/10
266/266 [==============================] - 8s 31ms/step - loss: 6.2497 - accuracy: 0.0980
Epoch 9/10
266/266 [==============================] - 8s 31ms/step - loss: 6.1625 - accuracy: 0.1016
Epoch 10/10
266/266 [==============================] - 8s 31ms/step - loss: 6.0773 - accur

In [24]:
model.fit(X,Y,epochs=1)

266/266 [==============================] - 8s 31ms/step - loss: 5.9818 - accuracy: 0.1054


In [25]:
model.compile(
    optimizer =tf.keras.optimizers.Adam(learning_rate=0.004),
    loss='categorical_crossentropy',
    metrics=['accuracy'])

In [26]:
model.fit(X,Y,epochs=10)

Epoch 1/10
266/266 [==============================] - 11s 31ms/step - loss: 6.4472 - accuracy: 0.1003
Epoch 2/10
266/266 [==============================] - 8s 31ms/step - loss: 6.1151 - accuracy: 0.1036
Epoch 3/10
266/266 [==============================] - 8s 31ms/step - loss: 5.9242 - accuracy: 0.1068
Epoch 4/10
266/266 [==============================] - 8s 31ms/step - loss: 5.7809 - accuracy: 0.1064
Epoch 5/10
266/266 [==============================] - 8s 31ms/step - loss: 5.6886 - accuracy: 0.1085
Epoch 6/10
266/266 [==============================] - 8s 31ms/step - loss: 5.5921 - accuracy: 0.1107
Epoch 7/10
266/266 [==============================] - 8s 31ms/step - loss: 5.5188 - accuracy: 0.1108
Epoch 8/10
266/266 [==============================] - 8s 31ms/step - loss: 5.4632 - accuracy: 0.1105
Epoch 9/10
266/266 [==============================] - 8s 31ms/step - loss: 5.4015 - accuracy: 0.1116
Epoch 10/10
266/266 [==============================] - 8s 32ms/step - loss: 5.3476 - accur

In [27]:
model.fit(X,Y,epochs=100)

Epoch 1/100
266/266 [==============================] - 8s 31ms/step - loss: 5.2959 - accuracy: 0.1151
Epoch 2/100
266/266 [==============================] - 8s 32ms/step - loss: 5.2417 - accuracy: 0.1148
Epoch 3/100
266/266 [==============================] - 8s 31ms/step - loss: 5.1887 - accuracy: 0.1176
Epoch 4/100
266/266 [==============================] - 8s 31ms/step - loss: 5.1456 - accuracy: 0.1172
Epoch 5/100
266/266 [==============================] - 9s 33ms/step - loss: 5.0986 - accuracy: 0.1189
Epoch 6/100
266/266 [==============================] - 8s 31ms/step - loss: 5.0566 - accuracy: 0.1220
Epoch 7/100
266/266 [==============================] - 8s 31ms/step - loss: 5.0235 - accuracy: 0.1224
Epoch 8/100
266/266 [==============================] - 8s 31ms/step - loss: 4.9824 - accuracy: 0.1208
Epoch 9/100
266/266 [==============================] - 8s 31ms/step - loss: 4.9406 - accuracy: 0.1219
Epoch 10/100
266/266 [==============================] - 8s 32ms/step - loss: 4.909

In [28]:
model.fit(X,Y,epochs=200)

Epoch 1/200
266/266 [==============================] - 8s 29ms/step - loss: 2.8403 - accuracy: 0.3402
Epoch 2/200
266/266 [==============================] - 8s 29ms/step - loss: 2.8155 - accuracy: 0.3429
Epoch 3/200
266/266 [==============================] - 8s 30ms/step - loss: 2.7865 - accuracy: 0.3547
Epoch 4/200
266/266 [==============================] - 8s 30ms/step - loss: 2.7874 - accuracy: 0.3475
Epoch 5/200
266/266 [==============================] - 8s 30ms/step - loss: 2.7879 - accuracy: 0.3436
Epoch 6/200
266/266 [==============================] - 8s 30ms/step - loss: 2.7871 - accuracy: 0.3495
Epoch 7/200
266/266 [==============================] - 8s 31ms/step - loss: 2.7891 - accuracy: 0.3491
Epoch 8/200
266/266 [==============================] - 8s 31ms/step - loss: 2.7441 - accuracy: 0.3533
Epoch 9/200
266/266 [==============================] - 8s 30ms/step - loss: 2.7490 - accuracy: 0.3575
Epoch 10/200
266/266 [==============================] - 8s 30ms/step - loss: 2.729

266/266 [==============================] - 11s 42ms/step - loss: 1.9881 - accuracy: 0.5153
Epoch 159/200
266/266 [==============================] - 11s 42ms/step - loss: 2.0036 - accuracy: 0.5114
Epoch 160/200
266/266 [==============================] - 11s 42ms/step - loss: 1.9579 - accuracy: 0.5223
Epoch 161/200
266/266 [==============================] - 11s 42ms/step - loss: 1.9245 - accuracy: 0.5352
Epoch 162/200
266/266 [==============================] - 12s 43ms/step - loss: 1.8918 - accuracy: 0.5406
Epoch 163/200
266/266 [==============================] - 13s 49ms/step - loss: 1.9013 - accuracy: 0.5377
Epoch 164/200
266/266 [==============================] - 11s 43ms/step - loss: 1.9210 - accuracy: 0.5341
Epoch 165/200
266/266 [==============================] - 11s 43ms/step - loss: 1.9293 - accuracy: 0.5288
Epoch 166/200
266/266 [==============================] - 12s 46ms/step - loss: 1.9892 - accuracy: 0.5186
Epoch 167/200
266/266 [==============================] - 12s 44ms/ste

In [30]:
model.save('nwp.h5')

In [33]:
vocab_array = np.array(list(tokenizer.word_index.keys()))

In [35]:
vocab_array

array(['the', 'of', 'a', ..., 'signed', 'sealed', 'delivered'],
      dtype='<U14')

In [39]:
def make_prediction(text, n_words):
    for i in range(n_words):
        text_tokenize = tokenizer.texts_to_sequences([text])[0]
        text_padded = tf.keras.preprocessing.sequence.pad_sequences
        print(text_tokenize)

In [44]:
def make_prediction(text, n_words):
    for i in range(n_words):
        text_tokenize = tokenizer.texts_to_sequences([text])
        text_padded = tf.keras.preprocessing.sequence.pad_sequences(text_tokenize, maxlen=14)
        print(text_padded)

In [46]:
make_prediction("john", 5)

[[  0   0   0   0   0   0   0   0   0   0   0   0   0 212]]
[[  0   0   0   0   0   0   0   0   0   0   0   0   0 212]]
[[  0   0   0   0   0   0   0   0   0   0   0   0   0 212]]
[[  0   0   0   0   0   0   0   0   0   0   0   0   0 212]]
[[  0   0   0   0   0   0   0   0   0   0   0   0   0 212]]


In [47]:
def make_prediction(text, n_words):
    for i in range(n_words):
        text_tokenize = tokenizer.texts_to_sequences([text])
        text_padded = tf.keras.preprocessing.sequence.pad_sequences(text_tokenize, maxlen=14)
        prediction=np.squeeze(np.argmax(model.predict(text_padded),axis=-1))
        prediction =str(vocab_array[prediction-1])
        text += " " + prediction
    return text

In [56]:
make_prediction("cloudy",5)

1/1 [==============================] - 0s 68ms/step


'cloudy with a chance of meatballs'

In [63]:
make_prediction("Harry",5)

1/1 [==============================] - 0s 45ms/step


'Harry potter and the museum time'